# Generated by Django 4.2.9 on 2024-02-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaapp', '0002_alter_zakaz_data_oplati_alter_zakaz_oplaceno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='data_oplati',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='oplaceno',
            field=models.BooleanField(default=False),
        ),
    ]
