# Generated by Django 4.2.9 on 2024-02-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaapp', '0003_alter_zakaz_data_oplati_alter_zakaz_oplaceno'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
